#! /usr/bin/env python

import sys
import extargsparse


def main():
	commandline='''
	{
		"verbose|v" : "+",
		"alternative|a" : false,
		"longoptions|l" : null,
		"name|n" : null,
		"options|o" : null,
		"quiet|q" : false,
		"quiet-output|Q" : false,
		"shell|s" : null,
		"test|T" : false,
		"unquoted|u" : false,
		"version|V" : false
	}
	'''
	parser = extargsparse.ExtArgsParse()
	parser.load_command_line_string(commandline)
	args= parser.parse_command_line()
	if args.version :
		print('getopt version 0.0.1')