#! /bin/bash

_script_file=`readlink -f $0`
script_dir=`dirname $_script_file`

templatefile="$1"
inputfile="$2"
outputfile="$3"

read -r -d '' AWK_REPL_STR<<EOFCC
{
	mexpr=sprintf(".*%s.*",replacekey);
	if (match(\$0,mexpr)) {
		gsub(replacekey,replacevalue);
		printf("%s\n",\$0);
	} else {
		printf("%s\n",\$0);
	}
}
EOFCC

tmpfile=`mktemp`
# first to input the value
cat "$templatefile" | sed 's/\\\\/%double_slash%/g' | sed 's/\\$/%endslash%/g' | sed 's/"\$/%quotedollar%/g'  | sed 's/\\\$/%dollarslash%/g' | sed 's/\\n/%newline%/g' | sed 's/\\/\\\\/g' | sed 's/\&/%specialcase%/g' > $tmpfile
replaceval=$(cat "$tmpfile" )
extargsversion=$(cat "$script_dir/VERSION")
awk -v replacekey='%EXTARGSPARSE%' -v replacevalue="$replaceval" "$AWK_REPL_STR" "$inputfile"  | awk -v replacekey='%EXTARGSPARSE4SH_VERSION%' -v replacevalue="$extargsversion"  "$AWK_REPL_STR" | sed 's/%newline%/\\n/g' |   sed 's/%endslash%/\\\\/g' |  sed 's/%dollarslash%/\\\\\\\$/g' | sed 's/%specialcase%/\&/g' | sed 's/%quotedollar%/"\\\$/g' | sed 's/%double_slash%/\\\\\\\\/g' >"$outputfile"
rm -f "$tmpfile"
#echo "tmpfile ($tmpfile)" >&2
